### ISSUE TITLE
Double clicking on form submission buttons reports two observations

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#100]
Solution would be to disable the used submit button with `this.disabled = "disabled";` in an event handler (pure JS for faster response). Would one of these handlers be the most proper?
https://github.com/wq/wq.app/blob/463c99a449333f4ea379efd7c98c42ec7996df47/js/wq/app.js#L233-L235
Maybe after evaluating `evt.isDefaultPrevented`?
https://github.com/wq/wq.app/blob/463c99a449333f4ea379efd7c98c42ec7996df47/js/wq/app.js#L1138-L1143

**Comment by sheppard** [comment]
This is fixed in [wq.app 1.1.1](https://github.com/wq/wq.app/releases/v1.1.1).
