### ISSUE TITLE
How to implement dependent/chained drop down list in new/edit form

### ISSUE THREAD

**Issue by mayank1989soni** [wq/wq.app#106]
I started working on wq quite recently and felt very promising for developing data collection apps.But I have a requirement of adding a chained dropdown in the new/edit form when the user selects Country, States should be filtered in the corresponding drop down. like Country USA State CA,MI,TX.....Please guide me.
Thanks # @sheppard @tomaszn

**Comment by tomaszn** [comment]
The only way I know to accomplish that is to write custom JS code, preferably as an "app plugin".
Documentation is at https://wq.io/1.0/docs/app-plugins , the most important part for you is "Full Example with AMD" and the "run" function.

**Comment by mayank1989soni** [comment]
Thank for your response.
Sure, I will go through.

**Comment by sheppard** [comment]
Thanks, yes the plugin is the way to go for now.
