### ISSUE TITLE
can_add / can_edit / can_delete flags not applied upon authentication

### ISSUE THREAD

**Issue by olivierdalang** [wq/wq.app#124]
Out of the box (wq 1.3.0a1), it seems can_add / can_edit / can_delete flags are not added even after login as superuser.
No "add" button appears on the list view, and not "edit" button in the detail view.

The buttons correctly appear and work when adding `can_add=True, can_edit=True` as arguments in rest.router.register_model (rest.py), but then obviously without taking the user permissions into account.

As discussed here :
https://github.com/wq/wq-django-template/issues/27#issuecomment-704294488

**Comment by sheppard** [comment]
This is fixed in [wq.app 1.3.0a2](https://github.com/wq/wq.app/releases/v1.3.0a2).
