### ISSUE TITLE
maketemplates and locate.js

### ISSUE THREAD

**Issue by tubaman** [wq/wq.app#126]
I've followed the [getting started](https://wq.io/1.1/docs/setup-local) guide.  I have a simple app up and running with a map.  What's the quickest way to add locate.js to that project?  I can't seem to get `maketemplates` to generate the [recommended locate.js HTML](https://wq.io/1.1/docs/locate-js).  

I basically want to use `wq addform` to create my form.  Whenever a Point field exists in the form, I want it to not only display a map but also the locate.js stuff formatted as recommended above.

**Comment by sheppard** [comment]
As of [wq.app 1.3 beta](https://github.com/wq/wq.app/releases/tag/v1.3.0b1), the new [Geo input](https://wq.io/inputs/Geo) now includes this UI by default.  Thanks for the suggestion!
