### ISSUE TITLE
Issue Running deploy.sh on OSX Mavericks with Python 2.7.5

### ISSUE THREAD

**Issue by joshglenn** [wq/wq.app#54]
I am currently trying to get wq.app and wq.db up-and-running on Mac OSX Mavericks. I am trying at the moment to run deploy.sh. When deploy, in turn, runs manage.py, I get this error:

```
env: python3: No such file or directory
```

This makes perfect sense, as I am not using python 3, but rather 2.7.5. So, I am wondering, should I upgrade to Python3, or can I simply change this directive ```#!/usr/bin/env python3``` to an identifier that references Pyhon 2.7.5?

Or... would I be better served running ubuntu 14.04 LTS like is used in all the documentation? (I'd rather not use a totally different os for development and have to use a whole new set of tools, but if I have to, I will). What do you think?

**Comment by sheppard** [comment]
If you remove the `3` it should pick up the default python installation.  I haven't tested much on OS X - but there isn't any particular reason it shouldn't work.  Any documentation about getting Django running on OS X would likely be applicable.

Eventually I would like to have section in the wq docs for OS X (see wq/wq#11), but for now Ubuntu 14.04 LTS is the most tested environment.

**Comment by joshglenn** [comment]
Removing the 3 worked, the deploy command was able to complete, with some errata, which I will discuss in other issues if it becomes necessary (they may not be real errors, but simply warnings). Thanks!
