### ISSUE TITLE
jquery mobile .ui-mobile-rendering and Seemingly Long Page Load Times

### ISSUE THREAD

**Issue by joshglenn** [wq/wq.app#55]
When I run the wq.app / wq.db django project using ``` db/manage.py runserver ```, then point my browser to the app, I'm getting what looks like a crazy long page load time. Although really it's not what it appears to be. When I load the page, it loads all of its js and css files, etc. That payload is 2.3 MB, and it takes about .8 seconds.

But, while the page is loading and for about four seconds thereafter,  the class ```.ui-mobile-rendering``` is added to the html element. So, all I see for those first five seconds total is a white page. I understand that is normal jquery mobile behaviour to add that class while the page is loading. But I'm wondering: if page load time is .8 seconds, why does the ```.ui-mobile-rendering``` class not get cleared from the html element for 5 seconds?

Is this happening because I am using the "runserver" command to do my testing? Should I be used a "real" apache web server for my testing server? Any thoughts on this?

**Comment by sheppard** [comment]
Yes, we usually use Apache rather than the runserver command - and not all of the paths to the js & css assets mapped to work within runserver.  So, it's interesting that the files are loading at all (they usually return 404s).  At any rate, it shouldn't take that long for the page to render.

**Comment by joshglenn** [comment]
I have this in my urls.py: 
```
if settings.DEBUG:

	# after building...
    urlpatterns += static('/css/', document_root=os.path.join(BASE_DIR, 'htdocs', 'css/'))
    urlpatterns += static('/images/', document_root=os.path.join(BASE_DIR, 'htdocs', 'images/'))
    urlpatterns += static('/js/', document_root=os.path.join(BASE_DIR, 'htdocs', 'js/'))
```.

I think this is what allows me to use the runserver command for debug testing. But I'm thinking that maybe the cache manifest is not being respected and a full page refresh is done on every page load. Not quite sure. Going to try using apache and see what happens.

**Comment by sheppard** [comment]
Okay, I tried doing the same and it worked, though it wasn't particularly slow.  Even with a full refresh it should still start up pretty fast since it's all local.  I'll have to try it out on a different machine.

Anyway, these url rules are probably worth including in the default template - see wq/wq.start#17.

**Comment by joshglenn** [comment]
Yeah, its strange. I have loaded seperately the species.wq.io example app. It loads fast, even in the testing server. But the boilerplate example app is slow as I described in the initial posting of this issue.

**Comment by joshglenn** [comment]
Not sure why but I haven't had any more trouble with this and have been using wq now for some time. Closing this issue.
