### ISSUE TITLE
Allow changing the next page after form submission with an attribute

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#78]
I wish to get back on the form for new items instantly after saving the current one.

I don't know how to do it now. The documentation of "postsave" hook says, that it can be used for that purpose, but no example is shown.

Maybe supporting a special attribute in the form of another attribute like data-nextpage="..." would be possible to easily implement?

**Comment by sheppard** [comment]
There are now two ways to use postsave, but only one way is documented at the moment.  The documented way is to use something that looks like a template name, e.g.:
 - `item_list` to return to the list view (default when background sync is on)
 - `item_detail` to display the newly saved item (default when background sync is off)

That wouldn't quite work for your case, but you can use the second way, which is just to provide a URL path (without the leading slash):

```python
# myapp/rest.py
rest.router.register_model(
   Item,
   postsave="items/new",
)
```

**Comment by tomaszn** [comment]
Thanks! And if I wanted to go to the_same_parent/parent_id/item/new?group=the_same_group?

**Comment by sheppard** [comment]
Try this:
`items/new?parent_id={{parent_id}}&group={{group}}`

**Comment by tomaszn** [comment]
Parameters from the query string don't seem to appear in the context. It would be a good and universal feature, I think.

**Comment by sheppard** [comment]
Yes, this is a bug - the context rendering feature currently only works after a successful sync (which in this case would require `wq-background-sync=false` to be set on the form).

The issue is here: https://github.com/wq/wq.app/blob/v1.0.0b2/js/wq/app.js#L373
```javascript
url = app.base_url + '/' + tmpl.render(postsave, item.result);
```
I think changing that line to this would work, though it will need some more testing:
```javascript
 url = app.base_url + '/' + tmpl.render(postsave, item.result || item.data);
```
