### ISSUE TITLE
"DELETE" method not supported in outbox (sent as PUT)

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#80]
In some scenarios removing items may be needed. 
I have a button to remove an item:
```html
<form action="{{svc}}/foos/{{id}}" method="delete" 
data-ajax="false" data-wq-json="true" ...(wq-outbox code)>
  <input type=hidden name="_method" value="DELETE">
  <button type="submit">Remove</button>
</form>
```
The request is still sent using the "PUT" method. If I edit the request and just change its method, it deletes the object successfully.

**Comment by sheppard** [comment]
Yes, this is due to a hardcoded "PUT" around line 1080 in [wq/app.js](https://github.com/wq/wq.app/blob/v1.0.0b2/js/wq/app.js#L1077-L1081).  That section should probably be changed to something like this:

```javascript
    if (vals._method) {
        options.method = vals._method;
        delete vals._method;
    } else {
        options.method = "POST";
    }
```

**Comment by tomaszn** [comment]
Thanks. The DELETE request is indeed sent now. Probably model updating code also needs some tuning, because there is also a unnecessary request made:
```
GET /<parent>//<my_objects>/
404 Not Found
```
(the form is on page `/<parent>/5/<my_objects>`)
and two errors in the console:
```
XML Parsing Error: no root element found 
Location: http://<server>/<my_objects>/28.json Line Number 1, Column 1
```
`TypeError: self.updateModels(...) is undefined`

Is there an easy way to fix the way refreshing models works in case of "DELETE"?

**Comment by sheppard** [comment]
Yes, the models lack a function to remove an element - which will need to be added.   We'll also need to think about how to configure the default postsave to handle this situation.

**Comment by tomaszn** [comment]
If using `postsave="sites/{{site_id}}/observations"` for Observation, then the (successful) DELETE operation tries to redirect to `sites//observations` and fails.
I'm using delete form from wq/xlsform-converter@e209a2d531a0baae97d4d46f4665c6450d29d3cb.

**Comment by sheppard** [comment]
You can use the new `postdelete` option which has a similar API.  I made `postdelete` default to `postsave` but now I'm thinking it should be entirely independent.

**Comment by tomaszn** [comment]
I think in `postdelete` these context variables are also not available (only the "deleted" one):
```
if (item.deletedId) {
   urlContext = {'deleted': true};
} else {
```

**Comment by sheppard** [comment]
Yeah that's a bit tricky since the `urlContext` is currently based on either the submitted form values, or the server response - both of which are effectively empty in the case of `DELETE`.  You could try pulling in the global "router_info" template variable instead:
```python
    postdelete="sites/{{router_info.context.site_id}}/observations"
```
`router_info.context` in this case refers to the last rendered context (i.e. for the current page).
