### ISSUE TITLE
"No image" placeholder visible when editing object with ImageField

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#81]
I am using automatically generated templates.
After saving an object with an image (django's ImageField) and starting to edit it, the previously saved image is not visible.
For example: https://try.wq.io/reports/36/edit

**Comment by sheppard** [comment]
Yes, this is in part due to the fact that the server doesn't fully support this either - see wq/wq.db#23.

**Comment by sheppard** [comment]
Ok, this is working now (though wq/wq.db#23 is still an issue).
