### ISSUE TITLE
Refer to new unsynced items from other new items

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#85]
I need to be able to create a set of items when offline (and have the references still working when the connection is established). Is it now possible?
It looks like the model API (e.g. "find" method) doesn't seem to find unsynced items.

**Comment by sheppard** [comment]
Yes, that is possible as of wq.app 1.0.0b2.  However, it does not work with the `[model].find()` API as of yet.  You can use the separate `[model].unsyncedItems()` to get at those records.  `unsyncedItems()` is called automatically during form rendering by the `_getOutboxRecords()` function in wq/app.js.  When used with the xlsconv 0.3.0 and newer templates, there should be a `*` next to any foreign key `<option>` that has not yet been synced.

Relevant commits:
https://github.com/wq/wq.app/commit/a968a75427a57d2635fabf7e05a227d0b2dd1ce9
https://github.com/wq/wq.app/commit/2bb1c31f851f2d954de24597d2deabd47c2cdcdf
https://github.com/wq/wq.app/commit/6fc734aa9136a0b2a1c37ea3931a4d4f39b5290b
https://github.com/wq/xlsform-converter/commit/b794a156a3a1d6d18ba64e6af093a2cc682df572

**Comment by sheppard** [comment]
When using the new IMMEDIATE mode for @wq/outbox, `find()` is able to see the unsynced records.  See #86.
