### ISSUE TITLE
Incorrect sync order of related outbox items (sendAll)

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#94]
When sending pending items, ones that depend on `id`s of other items should be postponed until what they refer to got their `id`s. I managed to get the batches of model names this way:
```
all_ready = [];
fresh = [];
do {
  new_ready = Object.values(app.config.pages).filter(function(page) {
    return page['list'] && !page.form.some(function(field) {
      return field['wq:ForeignKey'] && all_ready.indexOf(field['wq:ForeignKey']) == -1;
    });
  }).map(function(page) { return page['name']; });
  fresh = new_ready.filter(model => all_ready.indexOf(model) == -1);
  console.log('time to sync items from these models:', fresh);
  all_ready = new_ready;
} while (fresh.length);
```
After every item is synced, fields of relating items should be updated with a a persistent `id` obtained from the server.

**Comment by tomaszn** [comment]
Related to #85.

**Comment by tomaszn** [comment]
I think this was meant to be addressed by 2bb1c31f851f2d9, but `item.parents` are never set for use [here](https://github.com/wq/wq.app/commit/2bb1c31f851f2d954de24597d2deabd47c2cdcdf#diff-9bba13e47e8b25ad87341b0ea0459504R363).
Anyway, that solution would not start with syncing parents of parents, as is in my case.

**Comment by sheppard** [comment]
I created a test case for this in 45cd0c3 and it seems to be working.  Can you review and add more to the test, perhaps as part of #95?

I did find a bug while testing (see #102).

**Comment by sheppard** [comment]
This should be working pretty well now - see notes in #95.
