### ISSUE TITLE
ambiguous documentation for 'onsave' plugin callbacks

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#96]
The documentation should define when the `onsave` callbacks are run - before or after actually sending the pending items. Current outbox implementation runs all `onsave` plugins after the outbox items were sent and the local store is updated:

https://github.com/wq/wq.app/blob/463c99a449333f4ea379efd7c98c42ec7996df47/js/wq/app.js#L1393-L1397

**Comment by sheppard** [comment]
For version 1.2, I renamed this hook to "onsync" and updated the documentation.  As the new name reflects, it always runs after the item is sent to the server.
