### ISSUE TITLE
"list" views for offline items with offline parents are not redirected after parent is synced

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.app#98]
Given that parent and child records are synced properly (i.e. #94 is resolved), views like `parent/outbox-4/child_items` are refreshed when `data-wq-sync-refresh` is set to `true`, but the list appears empty, because the parent's id changes during the sync.

The sync-refresh functionality should take into account the synchronisation result and change the URL path properly.

**Comment by sheppard** [comment]
This is fixed now, thanks.
